/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse;

import fr.inria.diverse.AbstractLogoRuntimeModule;
import fr.inria.diverse.serialization.TransientValueService;
import org.eclipse.xtext.parsetree.reconstr.ITransientValueService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LogoRuntimeModule extends AbstractLogoRuntimeModule {
  @Override
  public Class<? extends ITransientValueService> bindITransientValueService() {
    return TransientValueService.class;
  }
}
