---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: completion
    name: completion
  spec:
    containers:
    - image: minijava/completion
      imagePullPolicy: IfNotPresent
      name: completion
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: completion
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: completion
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: definition
    name: definition
  spec:
    containers:
    - image: minijava/definition
      imagePullPolicy: IfNotPresent
      name: definition
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: definition
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: definition
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: highlight
    name: highlight
  spec:
    containers:
    - image: minijava/highlight
      imagePullPolicy: IfNotPresent
      name: highlight
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: highlight
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: highlight
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: hover
    name: hover
  spec:
    containers:
    - image: minijava/hover
      imagePullPolicy: IfNotPresent
      name: hover
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: hover
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hover
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: documentsymbol
    name: documentsymbol
  spec:
    containers:
    - image: minijava/documentsymbol
      imagePullPolicy: IfNotPresent
      name: documentsymbol
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: documentsymbol
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: documentsymbol
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: formatting
    name: formatting
  spec:
    containers:
    - image: minijava/formatting
      imagePullPolicy: IfNotPresent
      name: formatting
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: formatting
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: formatting
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: references
    name: references
  spec:
    containers:
    - image: minijava/references
      imagePullPolicy: IfNotPresent
      name: references
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: references
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: references
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: rename
    name: rename
  spec:
    containers:
    - image: minijava/rename
      imagePullPolicy: IfNotPresent
      name: rename
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: rename
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: rename
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: symbol
    name: symbol
  spec:
    containers:
    - image: minijava/symbol
      imagePullPolicy: IfNotPresent
      name: symbol
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: symbol
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: symbol
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: workspace
    name: workspace
  spec:
    containers:
    - image: minijava/workspace
      imagePullPolicy: IfNotPresent
      name: workspace
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: workspace
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: workspace
