---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: mongo-db
    name: mongo-db
  spec:
    containers:
    - image: mongo:4.0
      imagePullPolicy: IfNotPresent
      name: mongo-db
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: storage
    name: storage
  spec:
    containers:
    - image: kaulua/document-storage
      imagePullPolicy: IfNotPresent
      name: storage
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Pod"
  metadata:
    labels:
      app: router
    name: router
  spec:
    containers:
    - image: kaulua/lsp-router
      imagePullPolicy: IfNotPresent
      name: router
      ports: []
    nodeSelector:
      kaulua-selector: node1
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: mongo-db
  spec:
    type: NodePort
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo-db
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: storage
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: storage
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: router
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: router


