/**
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse;

import fr.inria.diverse.AbstractKauluaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KauluaRuntimeModule extends AbstractKauluaRuntimeModule {
}
