/**
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse;

import fr.inria.diverse.KauluaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KauluaStandaloneSetup extends KauluaStandaloneSetupGenerated {
  public static void doSetup() {
    new KauluaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
