/**
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse.ui;

import fr.inria.diverse.ui.AbstractKauluaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KauluaUiModule extends AbstractKauluaUiModule {
  public KauluaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
