/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.ide;

import fr.inria.diverse.ide.AbstractLogoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LogoIdeModule extends AbstractLogoIdeModule {
}
