/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.inria.diverse.LogoRuntimeModule;
import fr.inria.diverse.LogoStandaloneSetup;
import fr.inria.diverse.ide.LogoIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LogoIdeSetup extends LogoStandaloneSetup {
  @Override
  public Injector createInjector() {
    LogoRuntimeModule _logoRuntimeModule = new LogoRuntimeModule();
    LogoIdeModule _logoIdeModule = new LogoIdeModule();
    return Guice.createInjector(Modules2.mixin(_logoRuntimeModule, _logoIdeModule));
  }
}
