/**
 * generated by Xtext 2.14.0
 */
package fr.cea.nabla;

import fr.cea.nabla.NablaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class NablaStandaloneSetup extends NablaStandaloneSetupGenerated {
  public static void doSetup() {
    new NablaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
