/**
 * generated by Xtext 2.14.0
 */
package fr.cea.nabla;

import fr.cea.nabla.AbstractNablaRuntimeModule;
import fr.cea.nabla.formatting.SpaceFormatter;
import org.eclipse.xtext.formatting2.IFormatter2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NablaRuntimeModule extends AbstractNablaRuntimeModule {
  public Class<? extends IFormatter2> bindIFormatter2() {
    return SpaceFormatter.class;
  }
}
