---
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /publishDiagnostics:
    post:
      requestBody:
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/String'
      responses:
        201:
          description: Created
components:
  schemas:
    String:
      type: string
