FROM fabric8/java-centos-openjdk11-jre
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dfile.encoding=UTF-8"
ENV AB_ENABLED=jmx_exporter
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
COPY target/nablalib/* /deployments/nablalib/
EXPOSE 8080

ENTRYPOINT [ "/deployments/run-java.sh" ]