/**
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.inria.diverse.KauluaRuntimeModule;
import fr.inria.diverse.KauluaStandaloneSetup;
import fr.inria.diverse.ide.KauluaIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class KauluaIdeSetup extends KauluaStandaloneSetup {
  @Override
  public Injector createInjector() {
    KauluaRuntimeModule _kauluaRuntimeModule = new KauluaRuntimeModule();
    KauluaIdeModule _kauluaIdeModule = new KauluaIdeModule();
    return Guice.createInjector(Modules2.mixin(_kauluaRuntimeModule, _kauluaIdeModule));
  }
}
