/**
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse.ide;

import fr.inria.diverse.ide.AbstractKauluaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class KauluaIdeModule extends AbstractKauluaIdeModule {
}
